import '../models/vocabulary.dart';
import '../models/review_card.dart';
import '../data/database_helper.dart';

class SampleDataService {
  final DatabaseHelper _db = DatabaseHelper.instance;

  Future<void> initializeSampleData() async {
    final count = await _db.getTotalVocabularyCount();
    if (count > 0) return;

    final sampleVocab = [
      // Greetings & Common Expressions (10)
      Vocabulary(
        word: 'ありがとう',
        reading: 'arigatou',
        meaning: 'thank you',
        partOfSpeech: 'expression',
        exampleSentence: 'ありがとうございます',
        exampleReading: 'arigatou gozaimasu',
        exampleTranslation: 'Thank you very much',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: 'すみません',
        reading: 'sumimasen',
        meaning: 'excuse me, sorry',
        partOfSpeech: 'expression',
        exampleSentence: 'すみません、お願いします',
        exampleReading: 'sumimasen, onegai shimasu',
        exampleTranslation: 'Excuse me, please',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: 'おはよう',
        reading: 'ohayou',
        meaning: 'good morning',
        partOfSpeech: 'expression',
        exampleSentence: 'おはようございます',
        exampleReading: 'ohayou gozaimasu',
        exampleTranslation: 'Good morning (polite)',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: 'こんにちは',
        reading: 'konnichiwa',
        meaning: 'hello, good afternoon',
        partOfSpeech: 'expression',
        exampleSentence: 'こんにちは、元気ですか',
        exampleReading: 'konnichiwa, genki desu ka',
        exampleTranslation: 'Hello, how are you?',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: 'こんばんは',
        reading: 'konbanwa',
        meaning: 'good evening',
        partOfSpeech: 'expression',
        exampleSentence: 'こんばんは、お疲れ様です',
        exampleReading: 'konbanwa, otsukaresama desu',
        exampleTranslation: 'Good evening, thank you for your work',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: 'さようなら',
        reading: 'sayounara',
        meaning: 'goodbye',
        partOfSpeech: 'expression',
        exampleSentence: 'さようなら、また明日',
        exampleReading: 'sayounara, mata ashita',
        exampleTranslation: 'Goodbye, see you tomorrow',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: 'おやすみ',
        reading: 'oyasumi',
        meaning: 'good night',
        partOfSpeech: 'expression',
        exampleSentence: 'おやすみなさい',
        exampleReading: 'oyasuminasai',
        exampleTranslation: 'Good night (polite)',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: 'いただきます',
        reading: 'itadakimasu',
        meaning: 'let\'s eat (before meal)',
        partOfSpeech: 'expression',
        exampleSentence: 'いただきます',
        exampleReading: 'itadakimasu',
        exampleTranslation: 'Thank you for the meal (before eating)',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: 'ごちそうさま',
        reading: 'gochisousama',
        meaning: 'thank you for the meal (after)',
        partOfSpeech: 'expression',
        exampleSentence: 'ごちそうさまでした',
        exampleReading: 'gochisousama deshita',
        exampleTranslation: 'Thank you for the meal (after eating)',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: 'お願いします',
        reading: 'onegai shimasu',
        meaning: 'please (request)',
        partOfSpeech: 'expression',
        exampleSentence: 'これをお願いします',
        exampleReading: 'kore wo onegai shimasu',
        exampleTranslation: 'This one, please',
        jlptLevel: 'N5',
      ),
      // Basic Verbs (15)
      Vocabulary(
        word: '食べる',
        reading: 'taberu',
        meaning: 'to eat',
        partOfSpeech: 'verb',
        exampleSentence: 'ごはんを食べます',
        exampleReading: 'gohan wo tabemasu',
        exampleTranslation: 'I eat rice/meal',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '飲む',
        reading: 'nomu',
        meaning: 'to drink',
        partOfSpeech: 'verb',
        exampleSentence: '水を飲みます',
        exampleReading: 'mizu wo nomimasu',
        exampleTranslation: 'I drink water',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '学校',
        reading: 'gakkou',
        meaning: 'school',
        partOfSpeech: 'noun',
        exampleSentence: '学校に行きます',
        exampleReading: 'gakkou ni ikimasu',
        exampleTranslation: 'I go to school',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '本',
        reading: 'hon',
        meaning: 'book',
        partOfSpeech: 'noun',
        exampleSentence: '本を読みます',
        exampleReading: 'hon wo yomimasu',
        exampleTranslation: 'I read a book',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '見る',
        reading: 'miru',
        meaning: 'to see, to watch',
        partOfSpeech: 'verb',
        exampleSentence: 'テレビを見ます',
        exampleReading: 'terebi wo mimasu',
        exampleTranslation: 'I watch TV',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '行く',
        reading: 'iku',
        meaning: 'to go',
        partOfSpeech: 'verb',
        exampleSentence: '東京に行きます',
        exampleReading: 'toukyou ni ikimasu',
        exampleTranslation: 'I go to Tokyo',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '来る',
        reading: 'kuru',
        meaning: 'to come',
        partOfSpeech: 'verb',
        exampleSentence: '友達が来ます',
        exampleReading: 'tomodachi ga kimasu',
        exampleTranslation: 'My friend comes',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '帰る',
        reading: 'kaeru',
        meaning: 'to return, to go home',
        partOfSpeech: 'verb',
        exampleSentence: '家に帰ります',
        exampleReading: 'ie ni kaerimasu',
        exampleTranslation: 'I go home',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '友達',
        reading: 'tomodachi',
        meaning: 'friend',
        partOfSpeech: 'noun',
        exampleSentence: '友達と遊びます',
        exampleReading: 'tomodachi to asobimasu',
        exampleTranslation: 'I play with friends',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '買う',
        reading: 'kau',
        meaning: 'to buy',
        partOfSpeech: 'verb',
        exampleSentence: 'りんごを買います',
        exampleReading: 'ringo wo kaimasu',
        exampleTranslation: 'I buy apples',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '話す',
        reading: 'hanasu',
        meaning: 'to speak, to talk',
        partOfSpeech: 'verb',
        exampleSentence: '日本語を話します',
        exampleReading: 'nihongo wo hanashimasu',
        exampleTranslation: 'I speak Japanese',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '聞く',
        reading: 'kiku',
        meaning: 'to listen, to ask',
        partOfSpeech: 'verb',
        exampleSentence: '音楽を聞きます',
        exampleReading: 'ongaku wo kikimasu',
        exampleTranslation: 'I listen to music',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '書く',
        reading: 'kaku',
        meaning: 'to write',
        partOfSpeech: 'verb',
        exampleSentence: '手紙を書きます',
        exampleReading: 'tegami wo kakimasu',
        exampleTranslation: 'I write a letter',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '読む',
        reading: 'yomu',
        meaning: 'to read',
        partOfSpeech: 'verb',
        exampleSentence: '新聞を読みます',
        exampleReading: 'shinbun wo yomimasu',
        exampleTranslation: 'I read a newspaper',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '今日',
        reading: 'kyou',
        meaning: 'today',
        partOfSpeech: 'noun',
        exampleSentence: '今日は晴れです',
        exampleReading: 'kyou wa hare desu',
        exampleTranslation: 'Today is sunny',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '明日',
        reading: 'ashita',
        meaning: 'tomorrow',
        partOfSpeech: 'noun',
        exampleSentence: '明日は雨です',
        exampleReading: 'ashita wa ame desu',
        exampleTranslation: 'Tomorrow will be rainy',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '昨日',
        reading: 'kinou',
        meaning: 'yesterday',
        partOfSpeech: 'noun',
        exampleSentence: '昨日は休みでした',
        exampleReading: 'kinou wa yasumi deshita',
        exampleTranslation: 'Yesterday was a day off',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '時間',
        reading: 'jikan',
        meaning: 'time, hour',
        partOfSpeech: 'noun',
        exampleSentence: '時間がありません',
        exampleReading: 'jikan ga arimasen',
        exampleTranslation: 'I don\'t have time',
        jlptLevel: 'N5',
      ),
      // More Common Verbs
      Vocabulary(
        word: 'する',
        reading: 'suru',
        meaning: 'to do',
        partOfSpeech: 'verb',
        exampleSentence: '勉強をします',
        exampleReading: 'benkyou wo shimasu',
        exampleTranslation: 'I study',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '寝る',
        reading: 'neru',
        meaning: 'to sleep',
        partOfSpeech: 'verb',
        exampleSentence: '夜に寝ます',
        exampleReading: 'yoru ni nemasu',
        exampleTranslation: 'I sleep at night',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '起きる',
        reading: 'okiru',
        meaning: 'to wake up, to get up',
        partOfSpeech: 'verb',
        exampleSentence: '朝七時に起きます',
        exampleReading: 'asa shichiji ni okimasu',
        exampleTranslation: 'I wake up at 7 in the morning',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '待つ',
        reading: 'matsu',
        meaning: 'to wait',
        partOfSpeech: 'verb',
        exampleSentence: 'ここで待ちます',
        exampleReading: 'koko de machimasu',
        exampleTranslation: 'I wait here',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '分かる',
        reading: 'wakaru',
        meaning: 'to understand',
        partOfSpeech: 'verb',
        exampleSentence: '日本語が分かります',
        exampleReading: 'nihongo ga wakarimasu',
        exampleTranslation: 'I understand Japanese',
        jlptLevel: 'N5',
      ),
      // Common Nouns (10)
      Vocabulary(
        word: '人',
        reading: 'hito',
        meaning: 'person, people',
        partOfSpeech: 'noun',
        exampleSentence: 'あの人は先生です',
        exampleReading: 'ano hito wa sensei desu',
        exampleTranslation: 'That person is a teacher',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '水',
        reading: 'mizu',
        meaning: 'water',
        partOfSpeech: 'noun',
        exampleSentence: '水を飲みます',
        exampleReading: 'mizu wo nomimasu',
        exampleTranslation: 'I drink water',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: 'お茶',
        reading: 'ocha',
        meaning: 'tea',
        partOfSpeech: 'noun',
        exampleSentence: 'お茶をください',
        exampleReading: 'ocha wo kudasai',
        exampleTranslation: 'Tea, please',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: 'ご飯',
        reading: 'gohan',
        meaning: 'rice, meal',
        partOfSpeech: 'noun',
        exampleSentence: 'ご飯を食べます',
        exampleReading: 'gohan wo tabemasu',
        exampleTranslation: 'I eat rice/meal',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '家',
        reading: 'ie',
        meaning: 'house, home',
        partOfSpeech: 'noun',
        exampleSentence: '家に帰ります',
        exampleReading: 'ie ni kaerimasu',
        exampleTranslation: 'I go home',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '部屋',
        reading: 'heya',
        meaning: 'room',
        partOfSpeech: 'noun',
        exampleSentence: '部屋をきれいにします',
        exampleReading: 'heya wo kirei ni shimasu',
        exampleTranslation: 'I clean the room',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '先生',
        reading: 'sensei',
        meaning: 'teacher',
        partOfSpeech: 'noun',
        exampleSentence: '先生は日本人です',
        exampleReading: 'sensei wa nihonjin desu',
        exampleTranslation: 'The teacher is Japanese',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '学生',
        reading: 'gakusei',
        meaning: 'student',
        partOfSpeech: 'noun',
        exampleSentence: '私は学生です',
        exampleReading: 'watashi wa gakusei desu',
        exampleTranslation: 'I am a student',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '会社',
        reading: 'kaisha',
        meaning: 'company',
        partOfSpeech: 'noun',
        exampleSentence: '会社に行きます',
        exampleReading: 'kaisha ni ikimasu',
        exampleTranslation: 'I go to the company',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '駅',
        reading: 'eki',
        meaning: 'station',
        partOfSpeech: 'noun',
        exampleSentence: '駅まで歩きます',
        exampleReading: 'eki made arukimasu',
        exampleTranslation: 'I walk to the station',
        jlptLevel: 'N5',
      ),
      // Time Words (8)
      Vocabulary(
        word: '毎日',
        reading: 'mainichi',
        meaning: 'every day',
        partOfSpeech: 'noun',
        exampleSentence: '毎日勉強します',
        exampleReading: 'mainichi benkyou shimasu',
        exampleTranslation: 'I study every day',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '今',
        reading: 'ima',
        meaning: 'now',
        partOfSpeech: 'noun',
        exampleSentence: '今忙しいです',
        exampleReading: 'ima isogashii desu',
        exampleTranslation: 'I\'m busy now',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '朝',
        reading: 'asa',
        meaning: 'morning',
        partOfSpeech: 'noun',
        exampleSentence: '朝ご飯を食べます',
        exampleReading: 'asagohan wo tabemasu',
        exampleTranslation: 'I eat breakfast',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '昼',
        reading: 'hiru',
        meaning: 'afternoon, noon',
        partOfSpeech: 'noun',
        exampleSentence: '昼ご飯を食べます',
        exampleReading: 'hirugohan wo tabemasu',
        exampleTranslation: 'I eat lunch',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '夜',
        reading: 'yoru',
        meaning: 'night, evening',
        partOfSpeech: 'noun',
        exampleSentence: '夜ご飯を食べます',
        exampleReading: 'yorugohan wo tabemasu',
        exampleTranslation: 'I eat dinner',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '今週',
        reading: 'konshuu',
        meaning: 'this week',
        partOfSpeech: 'noun',
        exampleSentence: '今週は忙しいです',
        exampleReading: 'konshuu wa isogashii desu',
        exampleTranslation: 'This week is busy',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '来週',
        reading: 'raishuu',
        meaning: 'next week',
        partOfSpeech: 'noun',
        exampleSentence: '来週休みます',
        exampleReading: 'raishuu yasumimasu',
        exampleTranslation: 'I\'ll rest next week',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '先週',
        reading: 'senshuu',
        meaning: 'last week',
        partOfSpeech: 'noun',
        exampleSentence: '先週京都に行きました',
        exampleReading: 'senshuu kyouto ni ikimashita',
        exampleTranslation: 'I went to Kyoto last week',
        jlptLevel: 'N5',
      ),
      // Adjectives (7)
      Vocabulary(
        word: '大きい',
        reading: 'ookii',
        meaning: 'big, large',
        partOfSpeech: 'adjective',
        exampleSentence: '大きい家です',
        exampleReading: 'ookii ie desu',
        exampleTranslation: 'It\'s a big house',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '小さい',
        reading: 'chiisai',
        meaning: 'small',
        partOfSpeech: 'adjective',
        exampleSentence: '小さい犬です',
        exampleReading: 'chiisai inu desu',
        exampleTranslation: 'It\'s a small dog',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '新しい',
        reading: 'atarashii',
        meaning: 'new',
        partOfSpeech: 'adjective',
        exampleSentence: '新しい車です',
        exampleReading: 'atarashii kuruma desu',
        exampleTranslation: 'It\'s a new car',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '古い',
        reading: 'furui',
        meaning: 'old',
        partOfSpeech: 'adjective',
        exampleSentence: '古い本です',
        exampleReading: 'furui hon desu',
        exampleTranslation: 'It\'s an old book',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '良い',
        reading: 'yoi',
        meaning: 'good',
        partOfSpeech: 'adjective',
        exampleSentence: '良い天気です',
        exampleReading: 'yoi tenki desu',
        exampleTranslation: 'It\'s good weather',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '悪い',
        reading: 'warui',
        meaning: 'bad',
        partOfSpeech: 'adjective',
        exampleSentence: '悪い天気です',
        exampleReading: 'warui tenki desu',
        exampleTranslation: 'It\'s bad weather',
        jlptLevel: 'N5',
      ),
      Vocabulary(
        word: '美味しい',
        reading: 'oishii',
        meaning: 'delicious',
        partOfSpeech: 'adjective',
        exampleSentence: 'これは美味しいです',
        exampleReading: 'kore wa oishii desu',
        exampleTranslation: 'This is delicious',
        jlptLevel: 'N5',
      ),
    ];

    for (var vocab in sampleVocab) {
      final vocabId = await _db.insertVocabulary(vocab);

      final reviewCard = ReviewCard(
        vocabularyId: vocabId,
        repetitions: 0,
        easeFactor: 2.5,
        intervalDays: 1,
        nextReviewDate: DateTime.now(),
        lastReviewedAt: DateTime.now(),
      );

      await _db.insertReviewCard(reviewCard);
    }
  }
}
